Repository PathOfBuildingCommunity/PathOfBuilding-PoE2, pull requests merged in 2025-04, with the labels that each got.

#826 Implement Rare Templates
  src/Classes/ItemDBControl.lua
  src/Classes/ItemsTab.lua
  src/Data/Bases/body.lua
  src/Data/Bases/boots.lua
  src/Data/Bases/fishing.lua
  src/Data/Bases/flail.lua
  src/Data/Bases/gloves.lua
  src/Data/Bases/helmet.lua
  src/Data/Bases/sceptre.lua
  src/Data/Bases/shield.lua
  src/Data/Bases/staff.lua
  src/Data/Bases/sword.lua
  src/Data/ModCache.lua
  src/Data/Rares.lua
  src/Export/Bases/Rares.txt
  src/Export/Bases/body.txt
  src/Export/Bases/boots.txt
  src/Export/Bases/fishing.txt
  src/Export/Bases/flail.txt
  src/Export/Bases/gloves.txt
  src/Export/Bases/helmet.txt
  src/Export/Bases/sceptre.txt
  src/Export/Bases/shield.txt
  src/Export/Bases/staff.txt
  src/Export/Bases/sword.txt
  src/Export/Scripts/bases.lua
  src/Modules/Data.lua
  src/Modules/Main.lua
Labels: enhancement

#854 Update Unholy Might effect and tooltip
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#869 Add support for Siege Cascade dmg vs immobilised enemy
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/CalcSections.lua
Labels: enhancement

#868 Update Charge Duration, Unarmed Speed, and Cruel Ogham Manor reward
  src/Data/QuestRewards.lua
  src/Modules/CalcSetup.lua
  src/Modules/Data.lua
Labels: enhancement

#865 Add support for "Price Of Power" (Lich Ascendancy Notable)
  src/Modules/ModParser.lua
Labels: enhancement

#863 Add support for "Rupture The Soul" (Lich Ascendancy Notable)
  src/Modules/ModParser.lua
Labels: enhancement

#862 Add support for "Eldritch Empowerment" (Lich Ascendancy Notable)
  src/Modules/ModParser.lua
Labels: enhancement

#809 fix Weapon comparison with Giant's Blood
  src/Modules/CalcSetup.lua
Labels: bug: behaviour

#867 Toggle Attribute Nodes with Right Click
  CONTRIBUTING.md
  src/Classes/PassiveTreeView.lua
  src/Classes/TreeTab.lua
Labels: user-interface

#871 Add support for "A Solid Plan" - (Tactition Notable)
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#878 Add parsing for some new mods
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#883 Add nil check that causes load build to fail after corrupt build loaded
  src/Modules/Build.lua
Labels: technical

#879 Add support for "Critical Strike" (Amazon Ascendancy Notable)
  src/Modules/BuildDisplayStats.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#877 Add support for "Soulless Form" (Lich Ascendancy Notable)
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#876 Add Damage Buff for fully broken enemy armour
  src/Modules/CalcPerform.lua
Labels: bug: behaviour

#875 pinned enemies have no evasion
  src/Modules/ConfigOptions.lua
Labels: bug: behaviour

#845 Support importing characters from PoE API
  LICENSE.md
  runtime/lua/sha2.lua
  runtime/lua/socket.lua
  src/Classes/ImportTab.lua
  src/Classes/PassiveSpec.lua
  src/Classes/PassiveTree.lua
  src/Classes/PoEAPI.lua
  src/Classes/TradeQueryRateLimiter.lua
  src/Data/Global.lua
  src/Export/Scripts/passivetree.lua
  src/LaunchServer.lua
  src/Modules/Main.lua
  src/TreeData/0_1/tree.json
  src/TreeData/0_1/tree.lua
Labels: enhancement

#431 Only show bleed/ignite/poison options when needed
  src/Modules/ConfigOptions.lua
Labels: user-interface

#885 Add all new gems + support for the active ones
  src/Data/Gems.lua
  src/Data/Minions.lua
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/other.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Export/Minions/Minions.txt
  src/Export/Scripts/statdesc.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/minion.txt
  src/Export/Skills/other.txt
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_int.txt
  src/Export/Skills/sup_str.txt
  src/Export/spec.lua
  src/Modules/CalcOffence.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#857 Adds Support for Unfurled Finger and Mystic Attunement
  src/Classes/ImportTab.lua
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Classes/SkillListControl.lua
  src/Classes/SkillsTab.lua
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#818 Add support for various Crossbow mechanics (Reload Time, Additional Projectiles, Bolt Count, Mana costs, Fresh Clip Support))
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Data/Bases/crossbow.lua
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/other.lua
  src/Data/Skills/sup_str.lua
  src/Export/Scripts/bases.lua
  src/Export/Skills/other.txt
  src/Export/Skills/sup_str.txt
  src/Modules/BuildDisplayStats.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#880 Update some Uniques and create Variants
  src/Data/ModCache.lua
  src/Data/ModItemExclusive.lua
  src/Data/Uniques/Special/Generated.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/flask.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
  src/Export/Uniques/amulet.lua
  src/Export/Uniques/belt.lua
  src/Export/Uniques/body.lua
  src/Export/Uniques/bow.lua
  src/Export/Uniques/flask.lua
  src/Export/Uniques/gloves.lua
  src/Export/Uniques/helmet.lua
  src/Export/Uniques/mace.lua
  src/Export/Uniques/ring.lua
  src/Export/Uniques/shield.lua
  src/Export/Uniques/staff.lua
  src/Modules/ModParser.lua
Labels: enhancement

#887 Refactor ring effect code to reduce duplication
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: technical

#886 Add support for basic Companion nodes
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#888 Add support for Excoriate and Adhere
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
Labels: enhancement

#891 Add support for Parried Recently
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#890 Add support for Mysticism, Enormity, Strong Hearted, Loyalty, Overextend
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_int.txt
Labels: enhancement

#881 Add new Uniques
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/flask.lua
  src/Data/Uniques/focus.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/quiver.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/spear.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/wand.lua
  src/Export/Uniques/amulet.lua
  src/Export/Uniques/belt.lua
  src/Export/Uniques/body.lua
  src/Export/Uniques/bow.lua
  src/Export/Uniques/flask.lua
  src/Export/Uniques/focus.lua
  src/Export/Uniques/gloves.lua
  src/Export/Uniques/helmet.lua
  src/Export/Uniques/mace.lua
  src/Export/Uniques/quiver.lua
  src/Export/Uniques/ring.lua
  src/Export/Uniques/shield.lua
  src/Export/Uniques/spear.lua
  src/Export/Uniques/staff.lua
  src/Export/Uniques/wand.lua
Labels: enhancement

#893 Add support for a number of Support gems
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/other.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Export/Classes/GGPKData.lua
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_int.txt
  src/Export/Skills/sup_str.txt
  src/Export/spec.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#896 Fix Area and Projectile flags for many skills
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/other.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/other.txt
Labels: bug: calculation

#897 Fix damage flags on Considered Casting and Controlled Destruction
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
Labels: bug: behaviour

#901 fix: spelling
  CHANGELOG.md
  changelog.txt
Labels: technical

#912 Fix some support gems showing a stat requirement
  src/Classes/GemSelectControl.lua
  src/Classes/SkillsTab.lua
  src/Modules/CalcTools.lua
Labels: bug: behaviour

#910 Fix Quality of Sceptres affecting spirit total
  src/Classes/Item.lua
Labels: bug: calculation

#913 Add support for Infernalist's "Bringer of Flame" ascendancy
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#915 Fix calculation of Curse delay from support gems
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#916 Fix Heightened Curse not affecting Blasphemy Spirit cost
  src/Modules/CalcDefence.lua
Labels: bug: calculation

#920 Fix Stomping Ground damage calculatiion
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: bug: calculation

#919 Fix Smith's Masterwork not allowing you to allocate multiple nodes
  src/Classes/PassiveSpec.lua
  src/Export/Scripts/passivetree.lua
  src/TreeData/0_2/tree.json
  src/TreeData/0_2/tree.lua
Labels: bug: behaviour

#929 Fix Import for skills granted by items
  src/Classes/ImportTab.lua
Labels: bug: behaviour

#928 Fix crash when hovering over some jewel sockets with a 0.1 tree
  src/Classes/PassiveTreeView.lua
Labels: crash

#927 Fix crash when importing 0.1 characters that used old jewel sockets
  src/Classes/ImportTab.lua
Labels: crash

#926 Add support for "Curse Magnitudes"
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: accuracy

#924 Add support for Commandment, Reach, and various gem mods
  src/Data/Skills/act_int.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_int.txt
  src/Export/Skills/sup_str.txt
Labels: enhancement

#905 Fix some tree parsing in 0.2.0
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: accuracy

#898 Add 4 More Uniques
  src/Data/Uniques/Special/Generated.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/flask.lua
  src/Data/Uniques/focus.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/quiver.lua
  src/Data/Uniques/sceptre.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
  src/Export/Uniques/amulet.lua
  src/Export/Uniques/belt.lua
  src/Export/Uniques/body.lua
  src/Export/Uniques/boots.lua
  src/Export/Uniques/flask.lua
  src/Export/Uniques/focus.lua
  src/Export/Uniques/gloves.lua
  src/Export/Uniques/helmet.lua
  src/Export/Uniques/jewel.lua
  src/Export/Uniques/mace.lua
  src/Export/Uniques/quiver.lua
  src/Export/Uniques/sceptre.lua
  src/Export/Uniques/shield.lua
  src/Export/Uniques/staff.lua
Labels: enhancement

#922 Skeletal Warriors for Sceptres
  src/Data/Bases/sceptre.lua
  src/Data/Gems.lua
  src/Data/Minions.lua
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_int.lua
  src/Export/Minions/Minions.txt
  src/Export/Scripts/bases.lua
  src/Export/Skills/act_int.txt
  src/Export/spec.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#938 Add support for "Enemies you X have" and "Enemies you X cannot recharge energy shield"
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#939 Add Daze config and fix tree parsing for 0.2.0
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#940 Fix "increased Ailment chance" mods not working
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#941 Fix Rupture The Soul, Necromantic Conduit, Price of Power and Stay Light, Use Cover ascendancies not working
  src/Data/Gems.lua
  src/Data/ModCache.lua
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/ModParser.lua
Labels: bug: behaviour

#942 Add support for Amazon's Mystic Harvest and Stalking Panther nodes
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#943 Add support for player elemental Ailment Threshold calcs
  src/Data/ModCache.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#944 Fix "Could not generate search" error when using only full dps as a weight and not using full dps
  src/Classes/TradeQueryGenerator.lua
Labels: pob1, bug: behaviour

#946 Add support for Acolyte of Chayula's Ravenous Doubts node
  src/Data/ModCache.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#949 Fix Life cost calculation when using Sanguimancy and Archmage
  src/Data/ModCache.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#950 Add handling for +2 to Level of all Skills with a X requirement
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#951 Add support for Blood Mage's Blood Barbs and Between the Cracks nodes
  src/Data/ModCache.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#954 Add support for Accuracy Penalties at distance
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#952 Add resource lost information to enemy damage breakdown
  src/Modules/CalcDefence.lua
Labels: enhancement

#955 Add support for Gemling Legionnaire's Integrated Efficiency node
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#959 Add support for Deadly Herald
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
Labels: enhancement

#964 Update TradeQueryGenerator.lua with item subtypes
  src/Classes/TradeQueryGenerator.lua
  src/Data/QueryMods.lua
Labels: technical

#965 Fix Giant's Blood Keystone
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug: accuracy

#967 Add support for most Smith's Masterwork mods
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#960 Add support for Dread Banner ailment and stun threshold
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: enhancement

#978 Relocate code for addition of base weapon stats to CalcPerform
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
Labels: technical

#1002 Add support for Unerring Power
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
Labels: enhancement

#1001 Fix Recovery rate mods multiplying Life / Mana regeneration rate
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
Labels: bug: calculation

#1000 Fix Support Gem reservation multipliers
  src/Classes/GemSelectControl.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/sup_int.lua
  src/Export/Scripts/skills.lua
  src/Export/spec.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/Data.lua
Labels: bug: calculation

#988 Add support for Nightscale "cannot regen mana" mod
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#987 Add support for Gloamgown base ES Recharge Delay
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#977 Update trader to support PoE2 version of Megalomaniac
  src/Classes/Item.lua
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
  src/Data/QueryMods.lua
  src/Modules/CalcSetup.lua
Labels: enhancement

#973 Add support for Burgeon, Pinpoint Critical, Warm Blooded, and other partial gems
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_int.txt
  src/Modules/ModParser.lua
Labels: enhancement

#970 Fix a crash when importing a character with tree version 0_1 selected
  src/Classes/ImportTab.lua
Labels: crash

#969 Improve Accuracy Breakdown for Excess Hit Chance
  src/Modules/CalcOffence.lua
Labels: user-interface

#1005 Add support for Daevata's Wind "past 8 seconds" mod
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1004 Fix Arc skill on Storm Mages not working
  src/Data/Skills/minion.lua
  src/Export/Scripts/skills.lua
  src/Modules/CalcTools.lua
Labels: bug: calculation

#1008 Fix Cursecarver variants
  src/Data/ModCache.lua
  src/Data/Uniques/wand.lua
  src/Export/Uniques/wand.lua
  src/Modules/ModParser.lua
Labels: bug: accuracy

#1014 Fix Dauntless max damage stacking
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: bug: calculation

#1010 Add proper support for pasting items with lesser and greater runes
  src/Classes/Item.lua
Labels: enhancement

#1011 Add support for Eternal Life ascendancy notable
  src/Modules/Build.lua
  src/Modules/CalcDefence.lua
  src/Modules/Calcs.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1017 Add Weapon requirements to gem tooltip
  src/Classes/GemSelectControl.lua
  src/Data/Gems.lua
  src/Export/Scripts/skills.lua
Labels: enhancement, pob1

#1019 Fix Concoction skill Crit Chance and base damage
  src/Data/SkillStatMap.lua
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#1020 Fix Gem attack speed multiplier affecting Crossbow reload speed
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
Labels: pob1, bug: calculation

#1016 Fix ascendancy nodes position
  src/Classes/PassiveTree.lua
  src/Export/Scripts/passivetree.lua
  src/Export/spec.lua
  src/TreeData/0_2/tree.json
  src/TreeData/0_2/tree.lua
Labels: user-interface

#1032 Fix Eternal Life chaos damage resource drain breakdown
  src/Modules/CalcDefence.lua
Labels: bug: accuracy
