Repository PathOfBuildingCommunity/PathOfBuilding-PoE2, pull requests merged in 2025-10, with the labels that each got.

#1478 Add damage against Uniques on some skill gems
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
Labels: enhancement

#1477 Add support for Rigwald's Ferocity
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
Labels: enhancement

#1475 Add support for Embitter
  src/Data/ModCache.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/Data.lua
Labels: enhancement

#1473 Fix Fanatic Bow, Bolting Quarterstaff missing flat Elemental Damage
  src/Data/Bases/bow.lua
  src/Data/Bases/shield.lua
  src/Data/Bases/spear.lua
  src/Data/Bases/staff.lua
  src/Export/Bases/shield.txt
  src/Export/Bases/staff.txt
  src/Export/Scripts/bases.lua
Labels: bug: accuracy

#1470 Fix Revive Time calculation and show time for Spectres / Companion
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#1467 Update Spectres and World Areas to 0.3.1
  src/Data/Spectres.lua
  src/Data/WorldAreas.lua
  src/Export/Minions/SpectreList.txt
  src/Export/Minions/Spectres.txt
  src/Export/Scripts/worldAreas.lua
Labels: enhancement

#1463 Add copy button to exporter and increase script list size
  src/Export/Main.lua
Labels: pob1, technical, user-interface

#1456 Add "Base Damage" sorting option for Spectres
  src/Classes/MinionSearchListControl.lua
Labels: enhancement, user-interface

#1454 Add support for Shankgonne "you cannot sprint"
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1453 Add support for "duration of bleeding on you"
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement
