Repository PathOfBuildingCommunity/PathOfBuilding-PoE2, pull requests merged in 2025-09, with the labels that each got.

#1244 Fix invalid authentification URL being opened
  src/Classes/PoEAPI.lua
Labels: bug

#1252 Remove cap on "x% Armour applies to y Damage"
  src/Modules/CalcDefence.lua
Labels: bug: calculation

#1251 Add support for new "+X% of Armour also applies to Y Damage" mods
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1199 Show Influence icons on item headers
  spec/System/TestItemParse_spec.lua
  src/Assets/fractureditemsymbol.png
  src/Assets/veileditemsymbol.png
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Classes/Tooltip.lua
  src/Classes/TradeQueryRequests.lua
Labels: user-interface

#1259 Restore on-kill explosions support
  src/Data/ModCache.lua
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1250 Add support for "Sustainable Practices" (Pathfinder Ascendancy Node)
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1236 Update Minions and Spectres
  src/Classes/ImportTab.lua
  src/Data/Minions.lua
  src/Data/Spectres.lua
  src/Data/WorldAreas.lua
  src/Export/Minions/SpectreList.txt
  src/Export/Minions/Spectres.txt
  src/Export/Scripts/minions.lua
  src/Export/Scripts/spectreList.lua
  src/Export/Scripts/worldAreas.lua
  src/Export/spec.lua
Labels: enhancement

#1206 Add support for "Hollow Palm Technique" Keystone
  src/Data/Misc.lua
  src/Data/ModCache.lua
  src/Export/Scripts/miscdata.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1261 Update "item <defence>" related modifiers
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1270 Fix crash when allocating Answered Call
  src/Data/Minions.lua
Labels: crash

#1275 Implement Stoicism support and fix Innervate Support
  src/Data/SkillStatMap.lua
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
  src/Modules/ConfigOptions.lua
Labels: enhancement

#1277 Add Mask of the Sanguimancer Unique
  src/Data/Uniques/helmet.lua
  src/Export/Uniques/helmet.lua
Labels: enhancement

#1286 Fix incorrect radius on Explosive Spear
  src/Data/Skills/act_dex.lua
  src/Export/Scripts/skills.lua
Labels: bug: accuracy

#1292 Fix incorrect base types on Crown of Eyes and The Prisoner's Manacles
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Export/Uniques/gloves.lua
  src/Export/Uniques/helmet.lua
Labels: bug: calculation

#1291 Fix Herald of Blood buff not applying for conditional mods
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
Labels: bug: behaviour

#1287 Update Arcane Surge config tooltip
  src/Modules/CalcDefence.lua
  src/Modules/ConfigOptions.lua
Labels: user-interface

#1282 Fix Crash when using Bow with +1 Arrow Rune
  src/Classes/Item.lua
Labels: crash

#1276 Fix Heart of the Well modifier names
  src/Data/Uniques/Special/Generated.lua
Labels: bug: accuracy

#1303 Fix Crit chance for Spells with Infusion variants
  src/Data/Skills/act_int.lua
  src/Data/Skills/minion.lua
  src/Export/Scripts/skills.lua
Labels: bug: calculation

#1302 Fix quality stats on gems not showing up in gem tooltip
  src/Classes/GemSelectControl.lua
  src/Classes/SkillsTab.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/other.lua
  src/Export/Scripts/skills.lua
Labels: bug: behaviour

#1304 Fix display of some stats in gem tooltips
  src/Classes/GemSelectControl.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/ancestral_cry_projectile.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/ancestral_cry_statset_0.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/ball_lightning_statset_2.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/bone_cone.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/burst_shot_incendiary.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/create_mirage.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/dark_effigy_projectile.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/feast_of_flesh.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/foresight.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/frost_bomb.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/hand_of_chayula.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/igneous_shield.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/poisonbloom_arrow_statset_0.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/rapid_shot_permafrost.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/ravenous_swarm.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/reap.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/sorcery_ward.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/thunderfist_statset_1.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/toxic_domain_statset_0.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/toxic_domain_statset_1.lua
  src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/wrath_aura.lua
  src/Data/StatDescriptions/active_skill_gem_stat_descriptions.lua
  src/Data/StatDescriptions/meta_gem_stat_descriptions.lua
  src/Data/StatDescriptions/skill_stat_descriptions.lua
  src/Export/Scripts/statdesc.lua
  src/Export/statdesc.lua
  src/Modules/StatDescriber.lua
Labels: user-interface

#1332 Fix Totems using the wrong level for Life calculations
  src/Modules/CalcActiveSkill.lua
Labels: bug: behaviour

#1331 Add support for Ballista Nodes on the Tree
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1300 Add support for Deflection
  src/Modules/BuildDisplayStats.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1336 Fix Crash on Tree tab
  src/Classes/DropDownControl.lua
Labels: crash

#1334 Fix Requiem not showing damage values
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug: calculation

#746 Add support for Demon Form
  src/Data/ModCache.lua
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
  src/Modules/StatDescriber.lua
Labels: enhancement

#1338 Update Constricting Command unique helmet mod
  src/Data/Uniques/helmet.lua
  src/Export/Uniques/helmet.lua
Labels: bug: accuracy

#1280 Add support for Gigantic Following and fix Hulking Minions
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1339 Add breakdown for Daze Chance on Calcs tab
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: user-interface

#1341 Fix base modifiers showing up as explicit mods
  src/Classes/Item.lua
Labels: user-interface

#1344 fix: The Seven Pillars downsides
  src/Data/QuestRewards.lua
Labels: technical

#1362 Automatically check if the ModCache needs to be regenerated
  .github/workflows/test.yml
  src/Modules/Main.lua
Labels: technical

#1370 Fix trade search for Megalomaniac
  src/Classes/TradeQueryGenerator.lua
  src/Data/QueryMods.lua
Labels: bug: behaviour

#1372 Fix minion Gas Arrow skill not showing Poison / Explode damage
  src/Data/Skills/minion.lua
  src/Export/Skills/minion.txt
  src/Modules/CalcActiveSkill.lua
Labels: bug: calculation

#1363 Generate the changelog for the beta releases
  .github/tweak_changelogs.sh
  .github/workflows/beta.yml
  .github/workflows/release.yml
Labels: enhancement

#1355 Fix subscript errors
  src/Classes/ImportTab.lua
  src/Classes/PoEAPI.lua
  src/Launch.lua
  src/LaunchServer.lua
Labels: bug, pob1

#1376 Add support for Skills granted by The Unborn Lich staff
  src/Data/Gems.lua
  src/Data/ModCache.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: enhancement

#1382 Add support for Bonestorm, Flameblast, Incinerate, Supercharged Slam DPS
  src/Classes/GemSelectControl.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/other.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/other.txt
  src/Modules/Build.lua
  src/Modules/BuildDisplayStats.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#1383 Fix many Melee skills not hitting with both weapons when dual wielding
  src/Data/SkillStatMap.lua
Labels: bug: behaviour

#1384 Fix Crit Chance when hitting with 2 weapons at once
  src/Modules/CalcOffence.lua
Labels: pob1, bug: calculation

#1369 Add new Spectres from Act4 and Interlude
  src/Data/Global.lua
  src/Data/Minions.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/spectre.lua
  src/Data/Spectres.lua
  src/Export/Minions/SpectreList.txt
  src/Export/Minions/Spectres.txt
  src/Export/Skills/minion.txt
  src/Export/Skills/spectre.txt
  src/Modules/Data.lua
Labels: enhancement

#1388 Add passive tree search tip
  src/Classes/TreeTab.lua
Labels: user-interface

#1397 Fix Channel Time on Incinerate
  src/Modules/CalcOffence.lua
Labels: bug: behaviour

#1393 Fix Turtle Charm Max Block override not working
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
Labels: bug: behaviour

#1405 Load Crossbow Damage skills by default instead of Ammo Skill
  src/Classes/GemSelectControl.lua
  src/Data/Gems.lua
  src/Export/Scripts/skills.lua
  src/Export/spec.lua
  src/Modules/CalcSetup.lua
  src/Modules/Data.lua
Labels: bug: behaviour

#1403 Add Movement Speed while using skill to sidebar
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Modules/BuildDisplayStats.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1423 Add support for Rathpith Globe Life Cost mod
  src/Data/ModCache.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1435 Fix Prism of Belief + levels not working with some Skill Gems
  src/Data/Gems.lua
  src/Data/ModCache.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Uniques/Special/Generated.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Modules/ModParser.lua
Labels: bug: behaviour

#1432 Fix Skill Speed not affecting Totem Placement Speed
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/sup_dex.txt
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#1430 Fix Minion Reservation values + add Minion Count to breakdown
  src/Classes/CalcBreakdownControl.lua
  src/Modules/CalcDefence.lua
Labels: bug: calculation

#1428 Fix Crash when hovering over some Tree nodes with Hulking Form allocated
  src/Classes/ItemsTab.lua
  src/Classes/PassiveTreeView.lua
  src/Data/ModCache.lua
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/ModParser.lua
Labels: crash

#1439 Fix Header Influence Icon Showing on Jewel Sockets
  src/Classes/Tooltip.lua
Labels: user-interface

#1444 Add support for Bolt Speed
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1451 Fix display name for Blind II effect mod
  src/Data/SkillStatMap.lua
Labels: user-interface

#1445 Add support for Focused Curse
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
Labels: enhancement

#1446 Add support for Unbending
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1447 Fix Tooltip for Lich Socket
  src/Classes/PassiveTreeView.lua
Labels: user-interface

#1460 Make unset quest rewards more visible
  src/Modules/ConfigOptions.lua
Labels: user-interface
