Repository PathOfBuildingCommunity/PathOfBuilding-PoE2, pull requests merged in 2025-05, with the labels that each got.

#1074 Add support for "while wielding a Quarterstaff" (One with the River)
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1073 Add support for Doomfletch modifier
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1067 Add support for Shyaba "Always Hits"
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1065 Add support for Atziri's Acuity (Unique Gloves)
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1063 Add support for Blood Price reserved mod
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1062 Add support for Voltaic Mark shock effect
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#1061 Add support for Insulated Treads and "armour break on targets with ailments" node
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1059 Add support for Atsak's Sight (Unique Helmet)
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1057 Add support for "Zealous Inquisition" explode mod (Witchhunter Ascendancy Notable)
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1056 Add support for Voltaxic Rift shock chance mod
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1051 Parse "Cannot Use - Skills" modifiers
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1048 Fix banner valour config and tree nodes
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#1044 Fix calculation when using multiple "more Crit Damage Bonus" mods
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#1040 Added area tag to flicker strike
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug: calculation

#1039 Fix modifers to Blashpemy Spirit reservation applying to supported curses
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcDefence.lua
Labels: bug: calculation

#1034 Fix Rathpith Globe damage not working with Crown of Eyes
  src/Data/ModCache.lua
  src/Data/Uniques/helmet.lua
  src/Export/Uniques/helmet.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#1026 Rite of Passage and unique fixes
  src/Data/Uniques/Special/Generated.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/flask.lua
  src/Data/Uniques/focus.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/quiver.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/spear.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/wand.lua
  src/Export/Uniques/amulet.lua
  src/Export/Uniques/belt.lua
  src/Export/Uniques/body.lua
  src/Export/Uniques/bow.lua
  src/Export/Uniques/flask.lua
  src/Export/Uniques/focus.lua
  src/Export/Uniques/gloves.lua
  src/Export/Uniques/helmet.lua
  src/Export/Uniques/mace.lua
  src/Export/Uniques/quiver.lua
  src/Export/Uniques/ring.lua
  src/Export/Uniques/shield.lua
  src/Export/Uniques/spear.lua
  src/Export/Uniques/staff.lua
  src/Export/Uniques/wand.lua
Labels: enhancement

#1024 Add new keystones to "From Nothing" jewel
  src/Modules/Data.lua
Labels: bug: behaviour

#1054 Add support for Splinter of Loratta (Unique Spear)
  src/Data/ModCache.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1087 Fix Grasp of the Void damage gain not working correctly
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#1037 Add support for Lich Jewel Socket
  src/Classes/CalcBreakdownControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/PassiveTree.lua
  src/Classes/PassiveTreeView.lua
  src/Data/ModCache.lua
  src/Export/Scripts/passivetree.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
  src/TreeData/0_2/group-background_152_156_BC7.dds.zst
  src/TreeData/0_2/group-background_64_64_BC7.dds.zst
  src/TreeData/0_2/tree.json
  src/TreeData/0_2/tree.lua
Labels: enhancement

#1089 Fix Jewels missing many mods in item crafter
  src/Data/ModJewel.lua
  src/Export/Scripts/ScriptResources/JewelModWeights.lua
Labels: bug: accuracy

#1090 Fix many mods on jewels not being included in Weighted Search results
  src/Data/QueryMods.lua
Labels: bug: behaviour

#1091 Show Quiver Effect breakdown on Calcs Tab
  src/Modules/CalcSections.lua
Labels: user-interface

#1095 Add support for generic "DOUBLED" modForm
  docs/modSyntax.md
  src/Classes/ModDB.lua
  src/Classes/ModStore.lua
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: technical

#1094 Add support for "Presence" and related mods
  src/Data/ModCache.lua
  src/Modules/BuildDisplayStats.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1102 Add support for Essentia Sanguis leech mod
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1107 Fix Poisonburst Arrow not scaling with Skill Effect Duration
  src/Classes/CalcsTab.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: bug: calculation

#1100 Add support for Forking Critical Strikes
  src/Data/ModCache.lua
  src/Modules/BuildDisplayStats.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1108 Fix Discipline value being scaled by mods
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
Labels: bug: calculation

#1110 Fix Fractured mods not importing on items
  spec/System/TestItemParse_spec.lua
  src/Classes/ImportTab.lua
  src/Classes/Item.lua
  src/Modules/ItemTools.lua
Labels: bug: behaviour

#1111 Add support for Chaotic Might and fix Mjolner skill
  src/Data/Gems.lua
  src/Data/ModCache.lua
  src/Data/Skills/other.lua
  src/Data/Uniques/mace.lua
  src/Export/Skills/other.txt
  src/Export/Uniques/mace.lua
Labels: bug: accuracy

#1116 Fix crash due to outdated state of sub skill dropdown
  src/Modules/Build.lua
Labels: crash, user-interface

#1115 Fix crash when deleting newly created config set
  src/Classes/ConfigSetListControl.lua
Labels: crash, user-interface

#1113 Fix Beidat's Hand Energy Shield per Max Life mod not working
  src/Modules/CalcDefence.lua
Labels: bug: behaviour

#1114 Fix missing area base flag on concoction skills
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
Labels: bug: behaviour

#1119 Fix Against the Darkness using Medium radius instead of small
  src/Data/Uniques/Special/Generated.lua
Labels: bug: accuracy

#1144 Fix Stomping Ground not scaling with Melee Damage
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: bug: calculation

#1143 Fix some Relic items not counting as Unique
  src/Classes/ItemsTab.lua
  src/Modules/CalcPerform.lua
Labels: bug: behaviour

#1132 Fix support gems imported on skills from items causing an error
  src/Classes/ImportTab.lua
Labels: bug
