Repository PathOfBuildingCommunity/PathOfBuilding-PoE2, pull requests merged in 2025-01, with the labels that each got.

#390 Fix penetration calculations
  src/Modules/CalcBreakdown.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#400 Add support for Charge consumed recently tree nodes
  src/Modules/ModParser.lua
Labels: enhancement

#405 Add support for Controlled Destruction
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
Labels: enhancement

#399 Fix Archmage mana cost
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug: calculation

#398 Add support for Monk's Reality Rending node
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#395 Fix Scattershot Attack/Cast speed value
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
Labels: bug: calculation

#389 Fix Scaling of +Levels to Skill Modifiers
  src/Classes/ModStore.lua
Labels: bug: accuracy

#377 Add support for Unnatural Resilience notable
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#407 Fix Chain Support applying to all damage instead of just hits
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
Labels: bug: calculation

#408 Implement lua side hotkey for screenshots
  src/Launch.lua
Labels: technical

#410 Implement ability to delete folders with contents
  src/Classes/BuildListControl.lua
Labels: enhancement, user-interface

#411 Add support for Harness the Elements notable and Electrocute to config tab
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#418 Fix Ingenuity belt not working with reflected rings from Kalandra's Touch
  src/Modules/CalcPerform.lua
Labels: bug: behaviour

#422 fix parsing of some mods that have different wording on poe2
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#425 Fix passive nodes being permanently attached to a Weapon Set
  src/Classes/PassiveSpec.lua
  src/Classes/PassiveTreeView.lua
  src/Modules/CalcSetup.lua
Labels: bug: behaviour

#463 Add support for Grinning Immolation and Pain Attunement
  src/Modules/CalcOffence.lua
Labels: enhancement

#468 Add support for Kaom's Heart
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#467 Fix Maligaro's Virtuosity Critical Damage Bonus calculation
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#465 Fix Concoction skills not being treated as Unarmed
  src/Data/SkillStatMap.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
Labels: bug: behaviour

#435 Add Emotion filtering to Anoint popup
  src/Classes/CheckBoxControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/NotableDBControl.lua
Labels: enhancement, pob1

#476 Fix projectile scaling for Bonestorm and Gas Arrow
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
Labels: bug: behaviour

#475 improve implementation of Kaom's Heart 'You have no spirit' mod.
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#474 Add support for merging mods on nodes in radius of Time-Lost jewels
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#436 implemented support for 'Into the Breach' and 'Lucid Dreaming'
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#480 Fix crash when hovering over breakdown for Minion skills
  src/Modules/Data.lua
Labels: crash

#481 Add support for 'Allies in your presence' mods
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#482 Fix Minion Spell skills doing 0 damage
  src/Modules/CalcTools.lua
Labels: bug: calculation

#484 Add support for Armour Buff on Scavenged Plating
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/ConfigOptions.lua
Labels: enhancement

#508 Make Ice Bite work as intended
  src/Data/SkillStatMap.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_int.txt
Labels: bug: behaviour

#495 Add Stormweaver Scouring Winds mod Support
  src/Modules/ModParser.lua
Labels: enhancement

#492 fix 'Presence Present' notable and similar small nodes
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#489 fix spelling batch1
  changelog.txt
  spec/System/TestItemParse_spec.lua
  src/Classes/PassiveTree.lua
  src/Classes/SkillsTab.lua
  src/Classes/TradeQueryGenerator.lua
  src/Classes/TradeQueryRequests.lua
  src/Data/ModCache.lua
  src/Data/Uniques/ring.lua
  src/Export/Main.lua
  src/Export/Scripts/mods.lua
  src/Export/Scripts/skillGemList.lua
  src/Export/Uniques/ring.lua
  src/Export/statdesc.lua
  src/Modules/Build.lua
  src/Modules/CalcSetup.lua
  src/Modules/ItemTools.lua
Labels: technical

#513 Add support for Oasis keystone
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#530 improve "set up the exporter" tutorial
  CONTRIBUTING.md
Labels: documentation, technical

#529 Add clear button in dat viewer
  src/Export/Main.lua
Labels: pob1, technical

#553 Add tooltip to clarify distance to enemy units
  src/Modules/ConfigOptions.lua
Labels: user-interface

#551 Fix numbers not showing to correct decimal places in some UI modLines
  src/Modules/ItemTools.lua
Labels: user-interface

#512 feat: add "And protect me from harm" passive skill
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#533 Fix Corrupting cry using reduced effect instead of less
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: bug: calculation

#541 Add support for Deatonate Dead Corpse explosion calculation
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/sup_int.txt
  src/Modules/CalcOffence.lua
Labels: enhancement

#521 Add support for Mahuxotl's Machination
  src/Classes/Item.lua
  src/Data/ModCache.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#554 Add support for misc mods in Uniques and Tree
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#555 Reduce performance issues with Time-Lost Jewels
  src/Classes/ItemsTab.lua
  src/Classes/PassiveTreeView.lua
  src/Modules/CalcSetup.lua
  src/Modules/Common.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#563 Add support for additional empowering effects
  src/Data/ModCache.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_str.txt
  src/Modules/CalcActiveSkill.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#569 Update "Dmg. per ailment" title and ailment DPS beakdown titles
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: user-interface

#578 Fix Attack Damage mode missing from Ruby Jewel
  src/Data/ModCharm.lua
  src/Data/ModCorrupted.lua
  src/Data/ModFlask.lua
  src/Data/ModItem.lua
  src/Data/ModItemExclusive.lua
  src/Data/ModJewel.lua
  src/Export/Scripts/ScriptResources/JewelModWeights.lua
Labels: bug: accuracy

#580 Fix tooltips for passive node mods of type FLAG scaled by Hulking Form
  src/Classes/PassiveTreeView.lua
Labels: user-interface, bug: accuracy

#581 Fix Corrupted Unique roll ranges formula
  src/Modules/Common.lua
Labels: bug: calculation

#597 Fix Crash when switching between multiple choice Ascendancies
  src/Classes/PassiveSpec.lua
Labels: crash

#598 Add support for Offering skills AoE and Duration mods
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#600 update issue templates
  .github/ISSUE_TEMPLATE/accuracy_bug_report.yaml
  .github/ISSUE_TEMPLATE/application_bug_report.yaml
  .github/ISSUE_TEMPLATE/behaviour_bug_report.yaml
  .github/ISSUE_TEMPLATE/calculation_bug_report.yaml
  .github/ISSUE_TEMPLATE/crash_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: technical

#603 Add support for Inevitable Critical support gem
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
  src/Modules/ConfigOptions.lua
Labels: enhancement

#608 Support for Overabundance limit mod
  src/Data/SkillStatMap.lua
Labels: enhancement

#624 Add Shift + Ctrl + V to bypass item import confirmation box
  src/Classes/ItemsTab.lua
Labels: enhancement

#609 Make stack potential more understandable
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: user-interface

#612 Fix support gem counting when not enabled
  src/Classes/SkillsTab.lua
Labels: bug: behaviour

#629 Fix "from Equipped Shield" and add support for "from Equipped Focus"
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#627 Fix missing trade tags on certain items resulting in them not being generated.
  src/Classes/TradeQueryGenerator.lua
  src/Data/QueryMods.lua
Labels: bug: behaviour

#625 Add support for Monk's "Sunder my Enemies..." Invoker Ascendancy
  src/Data/ModCache.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#552 Improve EHP accuracy
  spec/System/TestDefence_spec.lua
  src/Modules/CalcDefence.lua
  src/Modules/Data.lua
Labels: bug: accuracy

#622 Update readme.md, contributing.md
  CONTRIBUTING.md
  README.md
  docker-compose.yml
Labels: documentation, technical

#630 Fix item range crash on ventor's gamble
  src/Modules/ItemTools.lua
Labels: bug, crash

#631 Parse Glancing Blows and Stand Ground
  src/Data/ModCache.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#639 Fix total flask charges gained in flask uptime calculation
  src/Classes/ItemsTab.lua
Labels: bug: calculation

#372 Fix fallout from SimpleGraphic upgrade with wider Unicode support
  Dockerfile
  src/Classes/EditControl.lua
  src/Modules/Common.lua
  src/UpdateCheck.lua
Labels: enhancement, user-interface

#653 Don't add stat comparisons for hovered gem quality if gem has no quality stats
  src/Classes/SkillsTab.lua
Labels: user-interface

#654 Fix Charge Infusion not working sometimes
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug: behaviour

#647 Dexterity added to Minions instead of accuracy
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: technical

#636 Add support for Dance with Death and Charm mods
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#635 Passive Tree Stuff
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#655 Added support for Minions "Life as extra ES" mod
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Modules/ModParser.lua
Labels: enhancement

#645 Add Support for Necromantic Talisman
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#621 Add support for Heroic Tragedy Timeless Jewel Keystones
  src/Classes/PassiveSpec.lua
  src/Classes/PassiveTree.lua
  src/Data/ModCache.lua
  src/Data/TimelessJewelData/LegionPassives.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#659 Fix Concoction skills not being treated as Unarmed
  src/Data/SkillStatMap.lua
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
Labels: bug: behaviour

#656 Support for Stars Aligned node
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#665 Fix Palm skills not scaling with unarmed damage
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug: calculation

#664 Fix Magma Barrier damage calculation
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug: calculation

#663 Fix Voltaic Nova and Freezing Nova damage scaling
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
Labels: bug: calculation

#662 Fix Herald of Thunder not using weapon damage
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug: calculation
