Repository PathOfBuildingCommunity/PathOfBuilding-PoE2, pull requests merged in 2025-03, with the labels that each got.

#816 Add support for Discipline
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: enhancement

#806 Fix Blasphemy's "Socketed Skills have +1 metres to base radius"
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: enhancement

#801 Fix "Exploit Weakness" Support not applying for "ArmourFullyBroken"
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: bug: behaviour

#797 Add support for Enfeeble "enemies deal less damage" mods
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/ConfigOptions.lua
Labels: enhancement

#793 Fix unleash seal gain time depends on base cast speed
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#791 Add support for Grenadier tree node
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#790 fix shockwave passive skill
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#786 Add support for "enemies in your presence have resistance equal to yours"
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#813 Add support for Berserk Gem
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: enhancement

#824 Add support for Sigil of Power
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: enhancement

#837 Add support for Saffel's Frame "max block mods apply to max resist"
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#784 Add support for Perfidy "% chance to avoid chaos damage from hits"
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#759 Add support for Break Enemy Armour Below 0 - "Imploding Impacts" Warbringer
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#756 Added support for break armour on hit
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#777 Add support for Attrition
  src/Classes/ModStore.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: enhancement

#835 Add support for Soul Core stat requirement conversion
  spec/System/TestItemParse_spec.lua
  src/Classes/Item.lua
  src/Modules/ModParser.lua
Labels: enhancement

#847 Add support for Minion Revival Time
  src/Data/ModCache.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#846 Add Base Attack Damage for Stomping Ground support
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: enhancement

#851 Fix Burden of Shadows Life cost calculation
  src/Data/ModCache.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#850 Rerun Node search when switching class
  src/Classes/PassiveTreeView.lua
  src/Modules/Build.lua
Labels: bug: behaviour

#843 Add support for Ice Crystal life
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/sup_int.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#839 support ailment part of overwhelming presence skill
  src/Data/SkillStatMap.lua
Labels: enhancement

#805 Fix warcry speed scaled by cast speed instead of warcry speed
  src/Modules/CalcOffence.lua
Labels: bug: calculation
