Repository PathOfBuildingCommunity/PathOfBuilding-PoE2, pull requests merged in 2025-08, with the labels that each got.

#1165 Add support for Deliberation Damage Mod
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
Labels: enhancement

#1153 Update EmmyLua VSCode debugging tutorial 2
  CONTRIBUTING.md
Labels: documentation, technical

#1184 Use Characters.ot and Monsters.ot files for many magic numbers
  src/Data/Misc.lua
  src/Export/Classes/GGPKData.lua
  src/Export/Scripts/miscdata.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
Labels: pob1, technical

#1182 fix: spelling efficiency/byrnabas
  spec/System/TestAttacks_spec.lua
  src/Data/FlavourText.lua
  src/Data/Uniques/belt.lua
  src/Export/Uniques/belt.lua
  src/Modules/CalcOffence.lua
Labels: technical

#1186 Fix automatically running character import on loading build, and show logout button in more cases
  src/Classes/ImportTab.lua
Labels: bug: behaviour

#1189 Fix Ascendancy header image and rename itemTooltip to tooltipHeader
  src/Assets/ascendancypassiveheaderleft.png
  src/Assets/ascendancypassiveheadermiddle.png
  src/Assets/ascendancypassiveheaderright.png
  src/Classes/GemSelectControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/PassiveTreeView.lua
  src/Classes/Tooltip.lua
Labels: user-interface

#1190 Fix vertical spacing and tooltip header size
  src/Classes/ItemsTab.lua
  src/Classes/Tooltip.lua
Labels: user-interface

#1198 Add Importing for Desecrated mods
  src/Classes/ImportTab.lua
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Classes/TradeQueryRequests.lua
  src/Data/Global.lua
  src/Modules/ItemTools.lua
Labels: enhancement

#1193 Implement Minions no longer need accuracy
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
Labels: enhancement

#1192 Change default Unarmed Crit to 5%
  spec/System/TestAttacks_spec.lua
  src/Modules/Data.lua
Labels: enhancement

#1207 Fix hover tooltip showing same name for all companions/spectres
  src/Classes/SkillsTab.lua
Labels: bug: accuracy

#1211 Add shortcut to copy node text from Passive Tree to the clipboard
  src/Classes/PassiveTreeView.lua
Labels: enhancement

#1214 Change wording for "Base Damage Reduction" on Hit taken mult. section
  src/Modules/CalcDefence.lua
Labels: user-interface, pob1-merged

#1215 Keep Max Price and Max Level between Trade Queries
  src/Classes/TradeQueryGenerator.lua
Labels: user-interface, pob1-merged

#1216 Add support for "reduced effect of freeze on you"
  src/Modules/ModParser.lua
Labels: enhancement, pob1-merged

#1210 Fix CI not working correctly with Ghostwrithe
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#1219 Sort Attribute Requirement List
  src/Modules/CalcPerform.lua
Labels: enhancement, pob1-merged

#1220 Fix Reduced Effect of Curses on Self not clamping
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
Labels: bug: behaviour, pob1-merged

#1221 Fix gems being added to skill groups when sorting dropdown
  src/Classes/GemSelectControl.lua
Labels: bug: behaviour, pob1-merged

#1222 Fix Item sort option for "Current Usable" not using taking into account attribute requirement mods
  src/Classes/ItemDBControl.lua
Labels: bug: behaviour, pob1-merged

#1226 Resume failed update feature
  src/UpdateCheck.lua
Labels: technical, pob1-merged

#1227 Fixed EHP based on block effect calculation
  src/Modules/CalcDefence.lua
Labels: bug: calculation, pob1-merged

#1194 Add support for "Apex of the Moment" (Chronomancer)
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1187 Add changes from 0.3 Patch Notes
  src/Data/Bases/axe.lua
  src/Data/Bases/body.lua
  src/Data/Bases/boots.lua
  src/Data/Bases/bow.lua
  src/Data/Bases/claw.lua
  src/Data/Bases/crossbow.lua
  src/Data/Bases/dagger.lua
  src/Data/Bases/fishing.lua
  src/Data/Bases/flail.lua
  src/Data/Bases/focus.lua
  src/Data/Bases/gloves.lua
  src/Data/Bases/helmet.lua
  src/Data/Bases/mace.lua
  src/Data/Bases/sceptre.lua
  src/Data/Bases/shield.lua
  src/Data/Bases/spear.lua
  src/Data/Bases/staff.lua
  src/Data/Bases/sword.lua
  src/Data/Bases/wand.lua
  src/Data/Misc.lua
  src/Data/ModItemExclusive.lua
  src/Data/ModJewel.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Export/Bases/axe.txt
  src/Export/Bases/body.txt
  src/Export/Bases/boots.txt
  src/Export/Bases/bow.txt
  src/Export/Bases/claw.txt
  src/Export/Bases/crossbow.txt
  src/Export/Bases/dagger.txt
  src/Export/Bases/fishing.txt
  src/Export/Bases/flail.txt
  src/Export/Bases/focus.txt
  src/Export/Bases/gloves.txt
  src/Export/Bases/helmet.txt
  src/Export/Bases/mace.txt
  src/Export/Bases/sceptre.txt
  src/Export/Bases/shield.txt
  src/Export/Bases/spear.txt
  src/Export/Bases/staff.txt
  src/Export/Bases/sword.txt
  src/Export/Bases/wand.txt
  src/Export/Scripts/ScriptResources/JewelModWeights.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
Labels: enhancement

#1172 0.3 - Update gem Attributes requirement formula
  src/Modules/CalcTools.lua
Labels: enhancement

#1228 Update Evasion / Hit Chance formula with 0.3 changes
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/Data.lua
Labels: enhancement

#1229 Update evasion to also apply to spell damage
  src/Modules/BuildDisplayStats.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#1231 Fix minion skill type issues causing mod compatiblity issues
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/other.lua
  src/Data/Skills/spectre.lua
  src/Export/Scripts/skills.lua
  src/Modules/CalcTools.lua
  src/Modules/CalcTriggers.lua
  src/Modules/Data.lua
Labels: bug: behaviour, pob1-merged

#1171 Update permissions for Linux
  .gitattributes
  CONTRIBUTING.md
  runtime/Path{space}of{space}Building-PoE2.exe
  runtime/Update.exe
Labels: pob1, technical

#1235 Export base items
  spec/System/TestItemParse_spec.lua
  src/Data/Bases/amulet.lua
  src/Data/Bases/axe.lua
  src/Data/Bases/body.lua
  src/Data/Bases/boots.lua
  src/Data/Bases/bow.lua
  src/Data/Bases/claw.lua
  src/Data/Bases/crossbow.lua
  src/Data/Bases/dagger.lua
  src/Data/Bases/flail.lua
  src/Data/Bases/flask.lua
  src/Data/Bases/focus.lua
  src/Data/Bases/gloves.lua
  src/Data/Bases/helmet.lua
  src/Data/Bases/mace.lua
  src/Data/Bases/quiver.lua
  src/Data/Bases/ring.lua
  src/Data/Bases/sceptre.lua
  src/Data/Bases/shield.lua
  src/Data/Bases/soulcore.lua
  src/Data/Bases/spear.lua
  src/Data/Bases/staff.lua
  src/Data/Bases/sword.lua
  src/Data/Bases/wand.lua
  src/Data/Rares.lua
  src/Export/Bases/sword.txt
  src/Export/Bases/wand.txt
  src/Export/Classes/GGPKData.lua
  src/Export/Scripts/bases.lua
  src/Export/spec.lua
Labels: enhancement
