Repository PathOfBuildingCommunity/PathOfBuilding-PoE2, pull requests merged in 2025-02, with the labels that each got.

#666 Added Support for Attacks Gain Extra mods on Quivers
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#667 Added support for Reduced Bleeding Duration on you
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#668 Added support for Trephina always deals crits against heavy stunned
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#669 Added support for Svalinn lucky block
  src/Data/ModCache.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#670 Added support for 25% of spell mana cost converted to life cost
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#672 Added support for Skin of the Loyal overcap mods
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#675 Added support for Iron Will and Iron Grip
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#676 Added support for Attack Speed when on full mana
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#681 Added support for Regenerative Flesh node
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#685 Add support for +Total Cast Time on Comet's and Lightning Conduit
  src/Data/SkillStatMap.lua
  src/Modules/CalcOffence.lua
Labels: enhancement

#687 Add support for Heavy Armour notable
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#690 Add/improve support for "ignore (non-negative) elemental resistances" mods [Heavy Frost, Choir of The Storm]
  src/Data/ModCache.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#692 Add support for Burden of Shadows 1% inc Chaos damage per 3 Life cost
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#678 Add support for increased Movement Speed while affected by an Ailment
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#694 Fix ES bypass regression from #552
  spec/System/TestDefence_spec.lua
  src/Modules/CalcDefence.lua
Labels: bug: calculation

#679 Added support for Minions resistances are equal to yours
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#689 Timeless Jewel Kalguur assets was added
  src/Classes/PassiveTreeView.lua
  src/Export/Scripts/passivetree.lua
  src/TreeData/0_1/legion_128_128_BC1.dds.zst
  src/TreeData/0_1/legion_1860_1864_BC7.dds.zst
  src/TreeData/0_1/legion_564_564_BC7.dds.zst
  src/TreeData/0_1/legion_64_64_BC1.dds.zst
  src/TreeData/0_1/legion_756_756_BC7.dds.zst
  src/TreeData/0_1/tree.json
  src/TreeData/0_1/tree.lua
Labels: enhancement

#698 Fix release notes
  .github/workflows/release.yml
  CHANGELOG.md
Labels: technical

#729 Fix the highlight node circle being too small
  src/Classes/PassiveTreeView.lua
Labels: user-interface

#728 Add support for Gamblesprint movement speed
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#725 Incorrect rounding for reservation
  src/Modules/CalcDefence.lua
Labels: bug: calculation

#723 Add support for Pinned recently
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#720 Added Support for extra exposure
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#709 Fix comparison tooltips for builds with Time-Lost Jewels
  src/Classes/ItemsTab.lua
  src/Classes/TreeTab.lua
  src/Modules/CalcSetup.lua
Labels: bug: calculation

#708 Added Support for life leech passive nodes
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#706 Add support for Vile Knight Enemy in Presence Duration mod
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#705 Added Support for "Slam skills have +% increased Area of Effect"
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#700 Add parsing for "Your speed is unaffected by Slows"
  src/Classes/ModStore.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#737 Fixup global variables
  src/Modules/CalcDefence.lua
Labels: enhancement, technical

#735 Fix crash from importing item with Mana leech mods
  src/Modules/ModParser.lua
Labels: crash

#733 Add support for Vulnerability" ignore x Armour" mod
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#731 Add support for Armour Break
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Modules/CalcOffence.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#734 Add support for "against enemies within/further than"
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#736 Fix Blasphemy not reserving Spirit
  spec/System/TestSkills_spec.lua
  src/Classes/SkillsTab.lua
  src/Data/ModCache.lua
  src/Data/Skills/act_int.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcDefence.lua
  src/Modules/Calcs.lua
  src/Modules/ModParser.lua
Labels: enhancement

#739 Fix caps
  src/Export/Classes/GGPKData.lua
Labels: technical

#741 Added support for ignore Warcry Cooldown
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#628 Add Support for Ailment chance calculations and Fix Shock calculation
  src/Data/Misc.lua
  src/Data/ModCache.lua
  src/Export/Scripts/miscdata.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#713 Update Exposure Values in ModParser
  src/Modules/ModParser.lua
Labels: technical

#752 Add support for War Banner aura mods
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/ConfigOptions.lua
Labels: enhancement

#750 Add support for Rolling Slam "more damage against heavy stunned enemies"
  src/Data/SkillStatMap.lua
Labels: enhancement

#753 Add support for Defiance Banner
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: enhancement

#758 Add support for "Electrocution" tree node
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#755 Add support for Break Armour on Critical Hit with Spells
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#767 Update Time-Lost Jewel affixes with proper wording
  src/Classes/ItemsTab.lua
  src/Modules/Data.lua
Labels: bug: accuracy

#766 Fix Blasphemy in act_int.txt
  src/Export/Skills/act_int.txt
Labels: technical

#763 Fix duplicate skill for Greater Lightning Bolt and Decompose
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: accuracy

#775 Add support for Candlemaker "chance to ignite is doubled"
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement
